# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: <span class="menu-link" style = "font-size:20px"> News </span>
    url: '#news'
    weight: 10
  - name: <span class="menu-link" style = "font-size:20px"> Publications </span>
    url: '#publications'
    weight: 20
  - name: <span class="menu-link" style = "font-size:20px"> Teaching </span>
    url: '#teaching'
    weight: 30
  - name: <span class="menu-link" style = "font-size:20px"> Contact </span>
    url: '#contact'
    weight: 40
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
